### ISSUE TITLE
Example values of nested objects are rendered as JSON with escaped <br> in them

### ISSUE THREAD

**Issue by alkemann** [Swagger2Markup/swagger2markup#282]
Consider a swagger that includes this on the a resource definition:

```yml
errorContext:
  type: object
  description: Map with additional error information
  example:
    field: currency
```

The markdown that is generated looks like this:

```markdown
|**errorContext**  <br>*optional*|**Example** : `{<br>  "field" : "currency",<br>  "message" : "Wrong currency code"<br>}`|object|
```

And this markdown gets converted into this HTML:

```html
<tr>
<td><strong>errorContext</strong>  <br><em>optional</em></td>
<td>Map with additional error information  <br><strong>Example</strong> : <code>{&lt;br&gt;  "field" : "currency"&lt;br&gt;}</code></td>
<td>object</td>
</tr>
```

Obviously the `&lt;br&gt;` in the JSON blobs are not desired.

**Comment by ljluestc** [comment]
```
errorContext:
  type: string
  description: Map with additional error information
  example: '{"field": "currency", "message": "Wrong currency code"}'

```
By enclosing the JSON example within double quotes and treating it as a string, you can avoid the unwanted <br> tags in the generated Markdown
`|errorContext <br>optional|Example : {"field": "currency", "message": "Wrong currency code"}|object|
`
