### ISSUE TITLE
Way to ignore some definitions in output

### ISSUE THREAD

**Issue by darkantoine** [Swagger2Markup/swagger2markup#351]
Hi,

I have a scenarios where I have defined a structure that I never use on its own but is included in other structures using allOf.

Dummy example:
```
Wheel:
  size: 
    type: string

Car: 
  allOf:
    - $ref:'#/definitions/Wheel'
    - properties:
         - engine: 
               type: string

Bike: 
  allOf:
    - $ref:'#/definitions/Wheel'
    - properties:
         - pedals: 
               type: string

```

Would there be a way to skip the "Wheel" Definition on its own in the output?
