### ISSUE TITLE
null values are cleaned out in adoc

### ISSUE THREAD

**Issue by IAmWebSA** [Swagger2Markup/swagger2markup#418]
Hello,

is there a way to keep the null values in the examples and do not remove them during conversation?

I have a yaml file which contains examples like:

 ```
examples:
            application/json:
              - value: null
                value2: 1
```

After running the convert the line with "value" is not present in the generated adoc file.
Is there a way to keep it as null without marking it as "null" string?

Adoc:
`[ {
  "value2" : 1,
}]`
